/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package sensor_msgs_msg

/*
#cgo LDFLAGS: "-L/usr/lib" "-Wl,-rpath=/usr/lib"
#cgo LDFLAGS: "-L/opt/ros/${ROS_DISTRO}/lib" "-Wl,-rpath=/opt/ros/${ROS_DISTRO}/lib"

#cgo LDFLAGS: -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lsensor_msgs__rosidl_typesupport_c -lsensor_msgs__rosidl_generator_c
#cgo LDFLAGS: -lbuiltin_interfaces__rosidl_typesupport_c -lbuiltin_interfaces__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: "-I/usr/include/action_msgs"
#cgo CFLAGS: "-I/usr/include/builtin_interfaces"
#cgo CFLAGS: "-I/usr/include/example_interfaces"
#cgo CFLAGS: "-I/usr/include/geometry_msgs"
#cgo CFLAGS: "-I/usr/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/usr/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/usr/include/sensor_msgs"
#cgo CFLAGS: "-I/usr/include/std_msgs"
#cgo CFLAGS: "-I/usr/include/std_srvs"
#cgo CFLAGS: "-I/usr/include/test_msgs"
#cgo CFLAGS: "-I/usr/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/usr/include/builtin_interfaces"

#cgo CFLAGS: "-I/usr/include/geometry_msgs"

#cgo CFLAGS: "-I/usr/include/std_msgs"

#cgo CFLAGS: "-I/usr/include/sensor_msgs"

#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/example_interfaces"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/geometry_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/sensor_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/std_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/std_srvs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/test_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/builtin_interfaces"

#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/geometry_msgs"

#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/std_msgs"

#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/sensor_msgs"
*/
import "C"
