/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package sensor_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <sensor_msgs/srv/set_camera_info.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("sensor_msgs/SetCameraInfo_Event", SetCameraInfo_EventTypeSupport)
	typemap.RegisterMessage("sensor_msgs/srv/SetCameraInfo_Event", SetCameraInfo_EventTypeSupport)
}

type SetCameraInfo_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []SetCameraInfo_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []SetCameraInfo_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewSetCameraInfo_Event creates a new SetCameraInfo_Event with default values.
func NewSetCameraInfo_Event() *SetCameraInfo_Event {
	self := SetCameraInfo_Event{}
	self.SetDefaults()
	return &self
}

func (t *SetCameraInfo_Event) Clone() *SetCameraInfo_Event {
	c := &SetCameraInfo_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]SetCameraInfo_Request, len(t.Request))
		CloneSetCameraInfo_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]SetCameraInfo_Response, len(t.Response))
		CloneSetCameraInfo_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *SetCameraInfo_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetCameraInfo_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *SetCameraInfo_Event) GetTypeSupport() types.MessageTypeSupport {
	return SetCameraInfo_EventTypeSupport
}

// SetCameraInfo_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetCameraInfo_EventPublisher struct {
	*rclgo.Publisher
}

// NewSetCameraInfo_EventPublisher creates and returns a new publisher for the
// SetCameraInfo_Event
func NewSetCameraInfo_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetCameraInfo_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetCameraInfo_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetCameraInfo_EventPublisher{pub}, nil
}

func (p *SetCameraInfo_EventPublisher) Publish(msg *SetCameraInfo_Event) error {
	return p.Publisher.Publish(msg)
}

// SetCameraInfo_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetCameraInfo_EventSubscription struct {
	*rclgo.Subscription
}

// SetCameraInfo_EventSubscriptionCallback type is used to provide a subscription
// handler function for a SetCameraInfo_EventSubscription.
type SetCameraInfo_EventSubscriptionCallback func(msg *SetCameraInfo_Event, info *rclgo.MessageInfo, err error)

// NewSetCameraInfo_EventSubscription creates and returns a new subscription for the
// SetCameraInfo_Event
func NewSetCameraInfo_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetCameraInfo_EventSubscriptionCallback) (*SetCameraInfo_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetCameraInfo_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetCameraInfo_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetCameraInfo_EventSubscription{sub}, nil
}

func (s *SetCameraInfo_EventSubscription) TakeMessage(out *SetCameraInfo_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetCameraInfo_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetCameraInfo_EventSlice(dst, src []SetCameraInfo_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetCameraInfo_EventTypeSupport types.MessageTypeSupport = _SetCameraInfo_EventTypeSupport{}

type _SetCameraInfo_EventTypeSupport struct{}

func (t _SetCameraInfo_EventTypeSupport) New() types.Message {
	return NewSetCameraInfo_Event()
}

func (t _SetCameraInfo_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.sensor_msgs__srv__SetCameraInfo_Event
	return (unsafe.Pointer)(C.sensor_msgs__srv__SetCameraInfo_Event__create())
}

func (t _SetCameraInfo_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.sensor_msgs__srv__SetCameraInfo_Event__destroy((*C.sensor_msgs__srv__SetCameraInfo_Event)(pointer_to_free))
}

func (t _SetCameraInfo_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetCameraInfo_Event)
	mem := (*C.sensor_msgs__srv__SetCameraInfo_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	SetCameraInfo_Request__Sequence_to_C(&mem.request, m.Request)
	SetCameraInfo_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _SetCameraInfo_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetCameraInfo_Event)
	mem := (*C.sensor_msgs__srv__SetCameraInfo_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	SetCameraInfo_Request__Sequence_to_Go(&m.Request, mem.request)
	SetCameraInfo_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _SetCameraInfo_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__srv__SetCameraInfo_Event())
}

type CSetCameraInfo_Event = C.sensor_msgs__srv__SetCameraInfo_Event
type CSetCameraInfo_Event__Sequence = C.sensor_msgs__srv__SetCameraInfo_Event__Sequence

func SetCameraInfo_Event__Sequence_to_Go(goSlice *[]SetCameraInfo_Event, cSlice CSetCameraInfo_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetCameraInfo_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetCameraInfo_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetCameraInfo_Event__Sequence_to_C(cSlice *CSetCameraInfo_Event__Sequence, goSlice []SetCameraInfo_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.sensor_msgs__srv__SetCameraInfo_Event)(C.malloc(C.sizeof_struct_sensor_msgs__srv__SetCameraInfo_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetCameraInfo_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetCameraInfo_Event__Array_to_Go(goSlice []SetCameraInfo_Event, cSlice []CSetCameraInfo_Event) {
	for i := 0; i < len(cSlice); i++ {
		SetCameraInfo_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetCameraInfo_Event__Array_to_C(cSlice []CSetCameraInfo_Event, goSlice []SetCameraInfo_Event) {
	for i := 0; i < len(goSlice); i++ {
		SetCameraInfo_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
