version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  settings:
    errcheck:
      exclude-functions:
        - github.com/spf13/viper.BindPFlag
        - github.com/spf13/viper.BindPFlags
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Debug
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Debugf
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Debugln
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Error
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Errorf
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Errorln
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Fatal
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Fatalf
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Fatalln
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Info
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Infof
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Infoln
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Warn
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Warnf
        - (*github.com/ATIinc/rclgo/pkg/rclgo.Logger).Warnln
        - github.com/ATIinc/rclgo/pkg/rclgo.Uninit
    errorlint:
      errorf: false
    gocritic:
      disabled-checks:
        - commentFormatting
        - dupSubExpr
        - ifElseChain
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1005
        - -ST1006
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'var-naming: don''t use underscores in Go names;'
      - path: (.+)\.go$
        text: 'error-strings: error strings should not be capitalized or end with punctuation or a newline'
      - path: (.+)\.go$
        text: 'err113: do not define dynamic errors, use wrapped static errors instead:'
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
      - path: (.+)\.go$
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
      - path: (.+)\.go$
        text: Use of unsafe calls should be audited
      - path: (.+)\.go$
        text: (G104|G307)
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
      - path: (.+)\.go$
        text: exported (.+) should have comment( \(or a comment on this block\))? or be unexported
      - path: (.+)\.go$
        text: package comment should be of the form "(.+)...
      - path: (.+)\.go$
        text: comment on exported (.+) should be of the form "(.+)..."
      - path: (.+)\.go$
        text: should have a package comment, unless it's in another file for this package
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
