/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package example_interfaces_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <example_interfaces/srv/add_two_ints.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("example_interfaces/AddTwoInts_Event", AddTwoInts_EventTypeSupport)
	typemap.RegisterMessage("example_interfaces/srv/AddTwoInts_Event", AddTwoInts_EventTypeSupport)
}

type AddTwoInts_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []AddTwoInts_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []AddTwoInts_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewAddTwoInts_Event creates a new AddTwoInts_Event with default values.
func NewAddTwoInts_Event() *AddTwoInts_Event {
	self := AddTwoInts_Event{}
	self.SetDefaults()
	return &self
}

func (t *AddTwoInts_Event) Clone() *AddTwoInts_Event {
	c := &AddTwoInts_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]AddTwoInts_Request, len(t.Request))
		CloneAddTwoInts_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]AddTwoInts_Response, len(t.Response))
		CloneAddTwoInts_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *AddTwoInts_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *AddTwoInts_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *AddTwoInts_Event) GetTypeSupport() types.MessageTypeSupport {
	return AddTwoInts_EventTypeSupport
}

// AddTwoInts_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type AddTwoInts_EventPublisher struct {
	*rclgo.Publisher
}

// NewAddTwoInts_EventPublisher creates and returns a new publisher for the
// AddTwoInts_Event
func NewAddTwoInts_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*AddTwoInts_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, AddTwoInts_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AddTwoInts_EventPublisher{pub}, nil
}

func (p *AddTwoInts_EventPublisher) Publish(msg *AddTwoInts_Event) error {
	return p.Publisher.Publish(msg)
}

// AddTwoInts_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type AddTwoInts_EventSubscription struct {
	*rclgo.Subscription
}

// AddTwoInts_EventSubscriptionCallback type is used to provide a subscription
// handler function for a AddTwoInts_EventSubscription.
type AddTwoInts_EventSubscriptionCallback func(msg *AddTwoInts_Event, info *rclgo.MessageInfo, err error)

// NewAddTwoInts_EventSubscription creates and returns a new subscription for the
// AddTwoInts_Event
func NewAddTwoInts_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback AddTwoInts_EventSubscriptionCallback) (*AddTwoInts_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg AddTwoInts_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, AddTwoInts_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &AddTwoInts_EventSubscription{sub}, nil
}

func (s *AddTwoInts_EventSubscription) TakeMessage(out *AddTwoInts_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneAddTwoInts_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneAddTwoInts_EventSlice(dst, src []AddTwoInts_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var AddTwoInts_EventTypeSupport types.MessageTypeSupport = _AddTwoInts_EventTypeSupport{}

type _AddTwoInts_EventTypeSupport struct{}

func (t _AddTwoInts_EventTypeSupport) New() types.Message {
	return NewAddTwoInts_Event()
}

func (t _AddTwoInts_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.example_interfaces__srv__AddTwoInts_Event
	return (unsafe.Pointer)(C.example_interfaces__srv__AddTwoInts_Event__create())
}

func (t _AddTwoInts_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.example_interfaces__srv__AddTwoInts_Event__destroy((*C.example_interfaces__srv__AddTwoInts_Event)(pointer_to_free))
}

func (t _AddTwoInts_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*AddTwoInts_Event)
	mem := (*C.example_interfaces__srv__AddTwoInts_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	AddTwoInts_Request__Sequence_to_C(&mem.request, m.Request)
	AddTwoInts_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _AddTwoInts_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*AddTwoInts_Event)
	mem := (*C.example_interfaces__srv__AddTwoInts_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	AddTwoInts_Request__Sequence_to_Go(&m.Request, mem.request)
	AddTwoInts_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _AddTwoInts_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__example_interfaces__srv__AddTwoInts_Event())
}

type CAddTwoInts_Event = C.example_interfaces__srv__AddTwoInts_Event
type CAddTwoInts_Event__Sequence = C.example_interfaces__srv__AddTwoInts_Event__Sequence

func AddTwoInts_Event__Sequence_to_Go(goSlice *[]AddTwoInts_Event, cSlice CAddTwoInts_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]AddTwoInts_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		AddTwoInts_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func AddTwoInts_Event__Sequence_to_C(cSlice *CAddTwoInts_Event__Sequence, goSlice []AddTwoInts_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.example_interfaces__srv__AddTwoInts_Event)(C.malloc(C.sizeof_struct_example_interfaces__srv__AddTwoInts_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		AddTwoInts_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func AddTwoInts_Event__Array_to_Go(goSlice []AddTwoInts_Event, cSlice []CAddTwoInts_Event) {
	for i := 0; i < len(cSlice); i++ {
		AddTwoInts_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func AddTwoInts_Event__Array_to_C(cSlice []CAddTwoInts_Event, goSlice []AddTwoInts_Event) {
	for i := 0; i < len(goSlice); i++ {
		AddTwoInts_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
