/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package example_interfaces_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <example_interfaces/srv/set_bool.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("example_interfaces/SetBool_Event", SetBool_EventTypeSupport)
	typemap.RegisterMessage("example_interfaces/srv/SetBool_Event", SetBool_EventTypeSupport)
}

type SetBool_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []SetBool_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []SetBool_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewSetBool_Event creates a new SetBool_Event with default values.
func NewSetBool_Event() *SetBool_Event {
	self := SetBool_Event{}
	self.SetDefaults()
	return &self
}

func (t *SetBool_Event) Clone() *SetBool_Event {
	c := &SetBool_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]SetBool_Request, len(t.Request))
		CloneSetBool_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]SetBool_Response, len(t.Response))
		CloneSetBool_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *SetBool_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetBool_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *SetBool_Event) GetTypeSupport() types.MessageTypeSupport {
	return SetBool_EventTypeSupport
}

// SetBool_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetBool_EventPublisher struct {
	*rclgo.Publisher
}

// NewSetBool_EventPublisher creates and returns a new publisher for the
// SetBool_Event
func NewSetBool_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetBool_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetBool_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetBool_EventPublisher{pub}, nil
}

func (p *SetBool_EventPublisher) Publish(msg *SetBool_Event) error {
	return p.Publisher.Publish(msg)
}

// SetBool_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetBool_EventSubscription struct {
	*rclgo.Subscription
}

// SetBool_EventSubscriptionCallback type is used to provide a subscription
// handler function for a SetBool_EventSubscription.
type SetBool_EventSubscriptionCallback func(msg *SetBool_Event, info *rclgo.MessageInfo, err error)

// NewSetBool_EventSubscription creates and returns a new subscription for the
// SetBool_Event
func NewSetBool_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetBool_EventSubscriptionCallback) (*SetBool_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetBool_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetBool_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetBool_EventSubscription{sub}, nil
}

func (s *SetBool_EventSubscription) TakeMessage(out *SetBool_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetBool_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetBool_EventSlice(dst, src []SetBool_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetBool_EventTypeSupport types.MessageTypeSupport = _SetBool_EventTypeSupport{}

type _SetBool_EventTypeSupport struct{}

func (t _SetBool_EventTypeSupport) New() types.Message {
	return NewSetBool_Event()
}

func (t _SetBool_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.example_interfaces__srv__SetBool_Event
	return (unsafe.Pointer)(C.example_interfaces__srv__SetBool_Event__create())
}

func (t _SetBool_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.example_interfaces__srv__SetBool_Event__destroy((*C.example_interfaces__srv__SetBool_Event)(pointer_to_free))
}

func (t _SetBool_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetBool_Event)
	mem := (*C.example_interfaces__srv__SetBool_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	SetBool_Request__Sequence_to_C(&mem.request, m.Request)
	SetBool_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _SetBool_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetBool_Event)
	mem := (*C.example_interfaces__srv__SetBool_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	SetBool_Request__Sequence_to_Go(&m.Request, mem.request)
	SetBool_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _SetBool_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__example_interfaces__srv__SetBool_Event())
}

type CSetBool_Event = C.example_interfaces__srv__SetBool_Event
type CSetBool_Event__Sequence = C.example_interfaces__srv__SetBool_Event__Sequence

func SetBool_Event__Sequence_to_Go(goSlice *[]SetBool_Event, cSlice CSetBool_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetBool_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetBool_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetBool_Event__Sequence_to_C(cSlice *CSetBool_Event__Sequence, goSlice []SetBool_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.example_interfaces__srv__SetBool_Event)(C.malloc(C.sizeof_struct_example_interfaces__srv__SetBool_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetBool_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetBool_Event__Array_to_Go(goSlice []SetBool_Event, cSlice []CSetBool_Event) {
	for i := 0; i < len(cSlice); i++ {
		SetBool_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetBool_Event__Array_to_C(cSlice []CSetBool_Event, goSlice []SetBool_Event) {
	for i := 0; i < len(goSlice); i++ {
		SetBool_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
