/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package example_interfaces_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <example_interfaces/srv/trigger.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("example_interfaces/Trigger_Event", Trigger_EventTypeSupport)
	typemap.RegisterMessage("example_interfaces/srv/Trigger_Event", Trigger_EventTypeSupport)
}

type Trigger_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []Trigger_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []Trigger_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewTrigger_Event creates a new Trigger_Event with default values.
func NewTrigger_Event() *Trigger_Event {
	self := Trigger_Event{}
	self.SetDefaults()
	return &self
}

func (t *Trigger_Event) Clone() *Trigger_Event {
	c := &Trigger_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]Trigger_Request, len(t.Request))
		CloneTrigger_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]Trigger_Response, len(t.Response))
		CloneTrigger_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *Trigger_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Trigger_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *Trigger_Event) GetTypeSupport() types.MessageTypeSupport {
	return Trigger_EventTypeSupport
}

// Trigger_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Trigger_EventPublisher struct {
	*rclgo.Publisher
}

// NewTrigger_EventPublisher creates and returns a new publisher for the
// Trigger_Event
func NewTrigger_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Trigger_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Trigger_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Trigger_EventPublisher{pub}, nil
}

func (p *Trigger_EventPublisher) Publish(msg *Trigger_Event) error {
	return p.Publisher.Publish(msg)
}

// Trigger_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Trigger_EventSubscription struct {
	*rclgo.Subscription
}

// Trigger_EventSubscriptionCallback type is used to provide a subscription
// handler function for a Trigger_EventSubscription.
type Trigger_EventSubscriptionCallback func(msg *Trigger_Event, info *rclgo.MessageInfo, err error)

// NewTrigger_EventSubscription creates and returns a new subscription for the
// Trigger_Event
func NewTrigger_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Trigger_EventSubscriptionCallback) (*Trigger_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Trigger_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Trigger_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Trigger_EventSubscription{sub}, nil
}

func (s *Trigger_EventSubscription) TakeMessage(out *Trigger_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneTrigger_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTrigger_EventSlice(dst, src []Trigger_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Trigger_EventTypeSupport types.MessageTypeSupport = _Trigger_EventTypeSupport{}

type _Trigger_EventTypeSupport struct{}

func (t _Trigger_EventTypeSupport) New() types.Message {
	return NewTrigger_Event()
}

func (t _Trigger_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.example_interfaces__srv__Trigger_Event
	return (unsafe.Pointer)(C.example_interfaces__srv__Trigger_Event__create())
}

func (t _Trigger_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.example_interfaces__srv__Trigger_Event__destroy((*C.example_interfaces__srv__Trigger_Event)(pointer_to_free))
}

func (t _Trigger_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Trigger_Event)
	mem := (*C.example_interfaces__srv__Trigger_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	Trigger_Request__Sequence_to_C(&mem.request, m.Request)
	Trigger_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _Trigger_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Trigger_Event)
	mem := (*C.example_interfaces__srv__Trigger_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	Trigger_Request__Sequence_to_Go(&m.Request, mem.request)
	Trigger_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _Trigger_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__example_interfaces__srv__Trigger_Event())
}

type CTrigger_Event = C.example_interfaces__srv__Trigger_Event
type CTrigger_Event__Sequence = C.example_interfaces__srv__Trigger_Event__Sequence

func Trigger_Event__Sequence_to_Go(goSlice *[]Trigger_Event, cSlice CTrigger_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Trigger_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Trigger_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Trigger_Event__Sequence_to_C(cSlice *CTrigger_Event__Sequence, goSlice []Trigger_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.example_interfaces__srv__Trigger_Event)(C.malloc(C.sizeof_struct_example_interfaces__srv__Trigger_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Trigger_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Trigger_Event__Array_to_Go(goSlice []Trigger_Event, cSlice []CTrigger_Event) {
	for i := 0; i < len(cSlice); i++ {
		Trigger_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Trigger_Event__Array_to_C(cSlice []CTrigger_Event, goSlice []Trigger_Event) {
	for i := 0; i < len(goSlice); i++ {
		Trigger_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
