/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package std_srvs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <std_srvs/srv/empty.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("std_srvs/Empty_Event", Empty_EventTypeSupport)
	typemap.RegisterMessage("std_srvs/srv/Empty_Event", Empty_EventTypeSupport)
}

type Empty_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []Empty_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []Empty_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewEmpty_Event creates a new Empty_Event with default values.
func NewEmpty_Event() *Empty_Event {
	self := Empty_Event{}
	self.SetDefaults()
	return &self
}

func (t *Empty_Event) Clone() *Empty_Event {
	c := &Empty_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]Empty_Request, len(t.Request))
		CloneEmpty_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]Empty_Response, len(t.Response))
		CloneEmpty_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *Empty_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Empty_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *Empty_Event) GetTypeSupport() types.MessageTypeSupport {
	return Empty_EventTypeSupport
}

// Empty_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Empty_EventPublisher struct {
	*rclgo.Publisher
}

// NewEmpty_EventPublisher creates and returns a new publisher for the
// Empty_Event
func NewEmpty_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Empty_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Empty_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Empty_EventPublisher{pub}, nil
}

func (p *Empty_EventPublisher) Publish(msg *Empty_Event) error {
	return p.Publisher.Publish(msg)
}

// Empty_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Empty_EventSubscription struct {
	*rclgo.Subscription
}

// Empty_EventSubscriptionCallback type is used to provide a subscription
// handler function for a Empty_EventSubscription.
type Empty_EventSubscriptionCallback func(msg *Empty_Event, info *rclgo.MessageInfo, err error)

// NewEmpty_EventSubscription creates and returns a new subscription for the
// Empty_Event
func NewEmpty_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Empty_EventSubscriptionCallback) (*Empty_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Empty_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Empty_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Empty_EventSubscription{sub}, nil
}

func (s *Empty_EventSubscription) TakeMessage(out *Empty_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneEmpty_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneEmpty_EventSlice(dst, src []Empty_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Empty_EventTypeSupport types.MessageTypeSupport = _Empty_EventTypeSupport{}

type _Empty_EventTypeSupport struct{}

func (t _Empty_EventTypeSupport) New() types.Message {
	return NewEmpty_Event()
}

func (t _Empty_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.std_srvs__srv__Empty_Event
	return (unsafe.Pointer)(C.std_srvs__srv__Empty_Event__create())
}

func (t _Empty_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.std_srvs__srv__Empty_Event__destroy((*C.std_srvs__srv__Empty_Event)(pointer_to_free))
}

func (t _Empty_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Empty_Event)
	mem := (*C.std_srvs__srv__Empty_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	Empty_Request__Sequence_to_C(&mem.request, m.Request)
	Empty_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _Empty_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Empty_Event)
	mem := (*C.std_srvs__srv__Empty_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	Empty_Request__Sequence_to_Go(&m.Request, mem.request)
	Empty_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _Empty_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__std_srvs__srv__Empty_Event())
}

type CEmpty_Event = C.std_srvs__srv__Empty_Event
type CEmpty_Event__Sequence = C.std_srvs__srv__Empty_Event__Sequence

func Empty_Event__Sequence_to_Go(goSlice *[]Empty_Event, cSlice CEmpty_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Empty_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Empty_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Empty_Event__Sequence_to_C(cSlice *CEmpty_Event__Sequence, goSlice []Empty_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.std_srvs__srv__Empty_Event)(C.malloc(C.sizeof_struct_std_srvs__srv__Empty_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Empty_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Empty_Event__Array_to_Go(goSlice []Empty_Event, cSlice []CEmpty_Event) {
	for i := 0; i < len(cSlice); i++ {
		Empty_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Empty_Event__Array_to_C(cSlice []CEmpty_Event, goSlice []Empty_Event) {
	for i := 0; i < len(goSlice); i++ {
		Empty_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
