/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package example_interfaces_action
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <example_interfaces/action/fibonacci.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("example_interfaces/Fibonacci_GetResult_Event", Fibonacci_GetResult_EventTypeSupport)
	typemap.RegisterMessage("example_interfaces/action/Fibonacci_GetResult_Event", Fibonacci_GetResult_EventTypeSupport)
}

type Fibonacci_GetResult_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []Fibonacci_GetResult_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []Fibonacci_GetResult_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewFibonacci_GetResult_Event creates a new Fibonacci_GetResult_Event with default values.
func NewFibonacci_GetResult_Event() *Fibonacci_GetResult_Event {
	self := Fibonacci_GetResult_Event{}
	self.SetDefaults()
	return &self
}

func (t *Fibonacci_GetResult_Event) Clone() *Fibonacci_GetResult_Event {
	c := &Fibonacci_GetResult_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]Fibonacci_GetResult_Request, len(t.Request))
		CloneFibonacci_GetResult_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]Fibonacci_GetResult_Response, len(t.Response))
		CloneFibonacci_GetResult_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *Fibonacci_GetResult_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Fibonacci_GetResult_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *Fibonacci_GetResult_Event) GetTypeSupport() types.MessageTypeSupport {
	return Fibonacci_GetResult_EventTypeSupport
}

// Fibonacci_GetResult_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Fibonacci_GetResult_EventPublisher struct {
	*rclgo.Publisher
}

// NewFibonacci_GetResult_EventPublisher creates and returns a new publisher for the
// Fibonacci_GetResult_Event
func NewFibonacci_GetResult_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Fibonacci_GetResult_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Fibonacci_GetResult_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Fibonacci_GetResult_EventPublisher{pub}, nil
}

func (p *Fibonacci_GetResult_EventPublisher) Publish(msg *Fibonacci_GetResult_Event) error {
	return p.Publisher.Publish(msg)
}

// Fibonacci_GetResult_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Fibonacci_GetResult_EventSubscription struct {
	*rclgo.Subscription
}

// Fibonacci_GetResult_EventSubscriptionCallback type is used to provide a subscription
// handler function for a Fibonacci_GetResult_EventSubscription.
type Fibonacci_GetResult_EventSubscriptionCallback func(msg *Fibonacci_GetResult_Event, info *rclgo.MessageInfo, err error)

// NewFibonacci_GetResult_EventSubscription creates and returns a new subscription for the
// Fibonacci_GetResult_Event
func NewFibonacci_GetResult_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Fibonacci_GetResult_EventSubscriptionCallback) (*Fibonacci_GetResult_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Fibonacci_GetResult_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Fibonacci_GetResult_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Fibonacci_GetResult_EventSubscription{sub}, nil
}

func (s *Fibonacci_GetResult_EventSubscription) TakeMessage(out *Fibonacci_GetResult_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFibonacci_GetResult_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFibonacci_GetResult_EventSlice(dst, src []Fibonacci_GetResult_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Fibonacci_GetResult_EventTypeSupport types.MessageTypeSupport = _Fibonacci_GetResult_EventTypeSupport{}

type _Fibonacci_GetResult_EventTypeSupport struct{}

func (t _Fibonacci_GetResult_EventTypeSupport) New() types.Message {
	return NewFibonacci_GetResult_Event()
}

func (t _Fibonacci_GetResult_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.example_interfaces__action__Fibonacci_GetResult_Event
	return (unsafe.Pointer)(C.example_interfaces__action__Fibonacci_GetResult_Event__create())
}

func (t _Fibonacci_GetResult_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.example_interfaces__action__Fibonacci_GetResult_Event__destroy((*C.example_interfaces__action__Fibonacci_GetResult_Event)(pointer_to_free))
}

func (t _Fibonacci_GetResult_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Fibonacci_GetResult_Event)
	mem := (*C.example_interfaces__action__Fibonacci_GetResult_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	Fibonacci_GetResult_Request__Sequence_to_C(&mem.request, m.Request)
	Fibonacci_GetResult_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _Fibonacci_GetResult_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Fibonacci_GetResult_Event)
	mem := (*C.example_interfaces__action__Fibonacci_GetResult_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	Fibonacci_GetResult_Request__Sequence_to_Go(&m.Request, mem.request)
	Fibonacci_GetResult_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _Fibonacci_GetResult_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__example_interfaces__action__Fibonacci_GetResult_Event())
}

type CFibonacci_GetResult_Event = C.example_interfaces__action__Fibonacci_GetResult_Event
type CFibonacci_GetResult_Event__Sequence = C.example_interfaces__action__Fibonacci_GetResult_Event__Sequence

func Fibonacci_GetResult_Event__Sequence_to_Go(goSlice *[]Fibonacci_GetResult_Event, cSlice CFibonacci_GetResult_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Fibonacci_GetResult_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Fibonacci_GetResult_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Fibonacci_GetResult_Event__Sequence_to_C(cSlice *CFibonacci_GetResult_Event__Sequence, goSlice []Fibonacci_GetResult_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.example_interfaces__action__Fibonacci_GetResult_Event)(C.malloc(C.sizeof_struct_example_interfaces__action__Fibonacci_GetResult_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Fibonacci_GetResult_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Fibonacci_GetResult_Event__Array_to_Go(goSlice []Fibonacci_GetResult_Event, cSlice []CFibonacci_GetResult_Event) {
	for i := 0; i < len(cSlice); i++ {
		Fibonacci_GetResult_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Fibonacci_GetResult_Event__Array_to_C(cSlice []CFibonacci_GetResult_Event, goSlice []Fibonacci_GetResult_Event) {
	for i := 0; i < len(goSlice); i++ {
		Fibonacci_GetResult_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
