/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package rclgo

/*
#cgo LDFLAGS: "-L/usr/lib" "-Wl,-rpath=/usr/lib"
#cgo CFLAGS: "-I/usr/include/rcl"
#cgo CFLAGS: "-I/usr/include/rmw"
#cgo CFLAGS: "-I/usr/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/usr/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/usr/include/rcutils"
#cgo CFLAGS: "-I/usr/include/rcl_action"
#cgo CFLAGS: "-I/usr/include/action_msgs"
#cgo CFLAGS: "-I/usr/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/usr/include/builtin_interfaces"
#cgo CFLAGS: "-I/usr/include/rcl_yaml_param_parser"

#cgo LDFLAGS: "-L/opt/ros/${ROS_DISTRO}/lib" "-Wl,-rpath=/opt/ros/${ROS_DISTRO}/lib"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rcl"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rmw"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rosidl_runtime_c"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rosidl_typesupport_interface"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rcutils"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rcl_action"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/action_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/unique_identifier_msgs"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/builtin_interfaces"
#cgo CFLAGS: "-I/opt/ros/${ROS_DISTRO}/include/rcl_yaml_param_parser"

#cgo LDFLAGS: -lrcl -lrmw -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrcl_action -lrmw_implementation
*/
import "C"
