/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package test_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <test_msgs/srv/arrays.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("test_msgs/Arrays_Event", Arrays_EventTypeSupport)
	typemap.RegisterMessage("test_msgs/srv/Arrays_Event", Arrays_EventTypeSupport)
}

type Arrays_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []Arrays_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []Arrays_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewArrays_Event creates a new Arrays_Event with default values.
func NewArrays_Event() *Arrays_Event {
	self := Arrays_Event{}
	self.SetDefaults()
	return &self
}

func (t *Arrays_Event) Clone() *Arrays_Event {
	c := &Arrays_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]Arrays_Request, len(t.Request))
		CloneArrays_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]Arrays_Response, len(t.Response))
		CloneArrays_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *Arrays_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Arrays_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *Arrays_Event) GetTypeSupport() types.MessageTypeSupport {
	return Arrays_EventTypeSupport
}

// Arrays_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Arrays_EventPublisher struct {
	*rclgo.Publisher
}

// NewArrays_EventPublisher creates and returns a new publisher for the
// Arrays_Event
func NewArrays_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Arrays_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Arrays_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Arrays_EventPublisher{pub}, nil
}

func (p *Arrays_EventPublisher) Publish(msg *Arrays_Event) error {
	return p.Publisher.Publish(msg)
}

// Arrays_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Arrays_EventSubscription struct {
	*rclgo.Subscription
}

// Arrays_EventSubscriptionCallback type is used to provide a subscription
// handler function for a Arrays_EventSubscription.
type Arrays_EventSubscriptionCallback func(msg *Arrays_Event, info *rclgo.MessageInfo, err error)

// NewArrays_EventSubscription creates and returns a new subscription for the
// Arrays_Event
func NewArrays_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Arrays_EventSubscriptionCallback) (*Arrays_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Arrays_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Arrays_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Arrays_EventSubscription{sub}, nil
}

func (s *Arrays_EventSubscription) TakeMessage(out *Arrays_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneArrays_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneArrays_EventSlice(dst, src []Arrays_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Arrays_EventTypeSupport types.MessageTypeSupport = _Arrays_EventTypeSupport{}

type _Arrays_EventTypeSupport struct{}

func (t _Arrays_EventTypeSupport) New() types.Message {
	return NewArrays_Event()
}

func (t _Arrays_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.test_msgs__srv__Arrays_Event
	return (unsafe.Pointer)(C.test_msgs__srv__Arrays_Event__create())
}

func (t _Arrays_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.test_msgs__srv__Arrays_Event__destroy((*C.test_msgs__srv__Arrays_Event)(pointer_to_free))
}

func (t _Arrays_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Arrays_Event)
	mem := (*C.test_msgs__srv__Arrays_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	Arrays_Request__Sequence_to_C(&mem.request, m.Request)
	Arrays_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _Arrays_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Arrays_Event)
	mem := (*C.test_msgs__srv__Arrays_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	Arrays_Request__Sequence_to_Go(&m.Request, mem.request)
	Arrays_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _Arrays_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__test_msgs__srv__Arrays_Event())
}

type CArrays_Event = C.test_msgs__srv__Arrays_Event
type CArrays_Event__Sequence = C.test_msgs__srv__Arrays_Event__Sequence

func Arrays_Event__Sequence_to_Go(goSlice *[]Arrays_Event, cSlice CArrays_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Arrays_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Arrays_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Arrays_Event__Sequence_to_C(cSlice *CArrays_Event__Sequence, goSlice []Arrays_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.test_msgs__srv__Arrays_Event)(C.malloc(C.sizeof_struct_test_msgs__srv__Arrays_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Arrays_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Arrays_Event__Array_to_Go(goSlice []Arrays_Event, cSlice []CArrays_Event) {
	for i := 0; i < len(cSlice); i++ {
		Arrays_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Arrays_Event__Array_to_C(cSlice []CArrays_Event, goSlice []Arrays_Event) {
	for i := 0; i < len(goSlice); i++ {
		Arrays_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
