/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package test_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <test_msgs/srv/basic_types.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("test_msgs/BasicTypes_Event", BasicTypes_EventTypeSupport)
	typemap.RegisterMessage("test_msgs/srv/BasicTypes_Event", BasicTypes_EventTypeSupport)
}

type BasicTypes_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []BasicTypes_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []BasicTypes_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewBasicTypes_Event creates a new BasicTypes_Event with default values.
func NewBasicTypes_Event() *BasicTypes_Event {
	self := BasicTypes_Event{}
	self.SetDefaults()
	return &self
}

func (t *BasicTypes_Event) Clone() *BasicTypes_Event {
	c := &BasicTypes_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]BasicTypes_Request, len(t.Request))
		CloneBasicTypes_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]BasicTypes_Response, len(t.Response))
		CloneBasicTypes_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *BasicTypes_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *BasicTypes_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *BasicTypes_Event) GetTypeSupport() types.MessageTypeSupport {
	return BasicTypes_EventTypeSupport
}

// BasicTypes_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type BasicTypes_EventPublisher struct {
	*rclgo.Publisher
}

// NewBasicTypes_EventPublisher creates and returns a new publisher for the
// BasicTypes_Event
func NewBasicTypes_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*BasicTypes_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, BasicTypes_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BasicTypes_EventPublisher{pub}, nil
}

func (p *BasicTypes_EventPublisher) Publish(msg *BasicTypes_Event) error {
	return p.Publisher.Publish(msg)
}

// BasicTypes_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type BasicTypes_EventSubscription struct {
	*rclgo.Subscription
}

// BasicTypes_EventSubscriptionCallback type is used to provide a subscription
// handler function for a BasicTypes_EventSubscription.
type BasicTypes_EventSubscriptionCallback func(msg *BasicTypes_Event, info *rclgo.MessageInfo, err error)

// NewBasicTypes_EventSubscription creates and returns a new subscription for the
// BasicTypes_Event
func NewBasicTypes_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback BasicTypes_EventSubscriptionCallback) (*BasicTypes_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg BasicTypes_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, BasicTypes_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &BasicTypes_EventSubscription{sub}, nil
}

func (s *BasicTypes_EventSubscription) TakeMessage(out *BasicTypes_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneBasicTypes_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBasicTypes_EventSlice(dst, src []BasicTypes_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BasicTypes_EventTypeSupport types.MessageTypeSupport = _BasicTypes_EventTypeSupport{}

type _BasicTypes_EventTypeSupport struct{}

func (t _BasicTypes_EventTypeSupport) New() types.Message {
	return NewBasicTypes_Event()
}

func (t _BasicTypes_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.test_msgs__srv__BasicTypes_Event
	return (unsafe.Pointer)(C.test_msgs__srv__BasicTypes_Event__create())
}

func (t _BasicTypes_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.test_msgs__srv__BasicTypes_Event__destroy((*C.test_msgs__srv__BasicTypes_Event)(pointer_to_free))
}

func (t _BasicTypes_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*BasicTypes_Event)
	mem := (*C.test_msgs__srv__BasicTypes_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	BasicTypes_Request__Sequence_to_C(&mem.request, m.Request)
	BasicTypes_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _BasicTypes_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*BasicTypes_Event)
	mem := (*C.test_msgs__srv__BasicTypes_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	BasicTypes_Request__Sequence_to_Go(&m.Request, mem.request)
	BasicTypes_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _BasicTypes_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__test_msgs__srv__BasicTypes_Event())
}

type CBasicTypes_Event = C.test_msgs__srv__BasicTypes_Event
type CBasicTypes_Event__Sequence = C.test_msgs__srv__BasicTypes_Event__Sequence

func BasicTypes_Event__Sequence_to_Go(goSlice *[]BasicTypes_Event, cSlice CBasicTypes_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BasicTypes_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		BasicTypes_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func BasicTypes_Event__Sequence_to_C(cSlice *CBasicTypes_Event__Sequence, goSlice []BasicTypes_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.test_msgs__srv__BasicTypes_Event)(C.malloc(C.sizeof_struct_test_msgs__srv__BasicTypes_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		BasicTypes_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func BasicTypes_Event__Array_to_Go(goSlice []BasicTypes_Event, cSlice []CBasicTypes_Event) {
	for i := 0; i < len(cSlice); i++ {
		BasicTypes_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func BasicTypes_Event__Array_to_C(cSlice []CBasicTypes_Event, goSlice []BasicTypes_Event) {
	for i := 0; i < len(goSlice); i++ {
		BasicTypes_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
