/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package test_msgs_action
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <test_msgs/action/nested_message.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("test_msgs/NestedMessage_SendGoal_Event", NestedMessage_SendGoal_EventTypeSupport)
	typemap.RegisterMessage("test_msgs/action/NestedMessage_SendGoal_Event", NestedMessage_SendGoal_EventTypeSupport)
}

type NestedMessage_SendGoal_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []NestedMessage_SendGoal_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []NestedMessage_SendGoal_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewNestedMessage_SendGoal_Event creates a new NestedMessage_SendGoal_Event with default values.
func NewNestedMessage_SendGoal_Event() *NestedMessage_SendGoal_Event {
	self := NestedMessage_SendGoal_Event{}
	self.SetDefaults()
	return &self
}

func (t *NestedMessage_SendGoal_Event) Clone() *NestedMessage_SendGoal_Event {
	c := &NestedMessage_SendGoal_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]NestedMessage_SendGoal_Request, len(t.Request))
		CloneNestedMessage_SendGoal_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]NestedMessage_SendGoal_Response, len(t.Response))
		CloneNestedMessage_SendGoal_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *NestedMessage_SendGoal_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *NestedMessage_SendGoal_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *NestedMessage_SendGoal_Event) GetTypeSupport() types.MessageTypeSupport {
	return NestedMessage_SendGoal_EventTypeSupport
}

// NestedMessage_SendGoal_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type NestedMessage_SendGoal_EventPublisher struct {
	*rclgo.Publisher
}

// NewNestedMessage_SendGoal_EventPublisher creates and returns a new publisher for the
// NestedMessage_SendGoal_Event
func NewNestedMessage_SendGoal_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*NestedMessage_SendGoal_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, NestedMessage_SendGoal_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NestedMessage_SendGoal_EventPublisher{pub}, nil
}

func (p *NestedMessage_SendGoal_EventPublisher) Publish(msg *NestedMessage_SendGoal_Event) error {
	return p.Publisher.Publish(msg)
}

// NestedMessage_SendGoal_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type NestedMessage_SendGoal_EventSubscription struct {
	*rclgo.Subscription
}

// NestedMessage_SendGoal_EventSubscriptionCallback type is used to provide a subscription
// handler function for a NestedMessage_SendGoal_EventSubscription.
type NestedMessage_SendGoal_EventSubscriptionCallback func(msg *NestedMessage_SendGoal_Event, info *rclgo.MessageInfo, err error)

// NewNestedMessage_SendGoal_EventSubscription creates and returns a new subscription for the
// NestedMessage_SendGoal_Event
func NewNestedMessage_SendGoal_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback NestedMessage_SendGoal_EventSubscriptionCallback) (*NestedMessage_SendGoal_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg NestedMessage_SendGoal_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, NestedMessage_SendGoal_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &NestedMessage_SendGoal_EventSubscription{sub}, nil
}

func (s *NestedMessage_SendGoal_EventSubscription) TakeMessage(out *NestedMessage_SendGoal_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneNestedMessage_SendGoal_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneNestedMessage_SendGoal_EventSlice(dst, src []NestedMessage_SendGoal_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var NestedMessage_SendGoal_EventTypeSupport types.MessageTypeSupport = _NestedMessage_SendGoal_EventTypeSupport{}

type _NestedMessage_SendGoal_EventTypeSupport struct{}

func (t _NestedMessage_SendGoal_EventTypeSupport) New() types.Message {
	return NewNestedMessage_SendGoal_Event()
}

func (t _NestedMessage_SendGoal_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.test_msgs__action__NestedMessage_SendGoal_Event
	return (unsafe.Pointer)(C.test_msgs__action__NestedMessage_SendGoal_Event__create())
}

func (t _NestedMessage_SendGoal_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.test_msgs__action__NestedMessage_SendGoal_Event__destroy((*C.test_msgs__action__NestedMessage_SendGoal_Event)(pointer_to_free))
}

func (t _NestedMessage_SendGoal_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*NestedMessage_SendGoal_Event)
	mem := (*C.test_msgs__action__NestedMessage_SendGoal_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	NestedMessage_SendGoal_Request__Sequence_to_C(&mem.request, m.Request)
	NestedMessage_SendGoal_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _NestedMessage_SendGoal_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*NestedMessage_SendGoal_Event)
	mem := (*C.test_msgs__action__NestedMessage_SendGoal_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	NestedMessage_SendGoal_Request__Sequence_to_Go(&m.Request, mem.request)
	NestedMessage_SendGoal_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _NestedMessage_SendGoal_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__test_msgs__action__NestedMessage_SendGoal_Event())
}

type CNestedMessage_SendGoal_Event = C.test_msgs__action__NestedMessage_SendGoal_Event
type CNestedMessage_SendGoal_Event__Sequence = C.test_msgs__action__NestedMessage_SendGoal_Event__Sequence

func NestedMessage_SendGoal_Event__Sequence_to_Go(goSlice *[]NestedMessage_SendGoal_Event, cSlice CNestedMessage_SendGoal_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]NestedMessage_SendGoal_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		NestedMessage_SendGoal_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func NestedMessage_SendGoal_Event__Sequence_to_C(cSlice *CNestedMessage_SendGoal_Event__Sequence, goSlice []NestedMessage_SendGoal_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.test_msgs__action__NestedMessage_SendGoal_Event)(C.malloc(C.sizeof_struct_test_msgs__action__NestedMessage_SendGoal_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		NestedMessage_SendGoal_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func NestedMessage_SendGoal_Event__Array_to_Go(goSlice []NestedMessage_SendGoal_Event, cSlice []CNestedMessage_SendGoal_Event) {
	for i := 0; i < len(cSlice); i++ {
		NestedMessage_SendGoal_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func NestedMessage_SendGoal_Event__Array_to_C(cSlice []CNestedMessage_SendGoal_Event, goSlice []NestedMessage_SendGoal_Event) {
	for i := 0; i < len(goSlice); i++ {
		NestedMessage_SendGoal_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
