name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/tiiuae/fog-ros-baseimage-builder:dp-4266_humble_upgrade
    steps:
      - uses: actions/checkout@v2

      - name: Install additional tools and libraries
        run: |
          apt-get update
          apt-get install -y \
            make \
            ros-humble-action-msgs \
            ros-humble-example-interfaces \
            ros-humble-test-msgs

      - name: Run tests
        run: make test

  run-linter:
    runs-on: ubuntu-latest
    container: ghcr.io/tiiuae/fog-ros-baseimage-builder:dp-4266_humble_upgrade
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        shell: bash
        run: |
          apt-get update
          apt-get install -y \
            ros-humble-action-msgs \
            ros-humble-example-interfaces \
            ros-humble-test-msgs
          env > "$GITHUB_ENV"

      - uses: golangci/golangci-lint-action@v2
