name: main

env:
  ROS_DISTRO: kilted

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ros:kilted
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'
          check-latest: true

      - name: Install additional tools and libraries
        run: |
          apt-get update
          apt-get install -y \
            make \
            ros-kilted-action-msgs \
            ros-kilted-example-interfaces \
            ros-kilted-test-msgs

      - name: Run tests
        run: make test

  run-linter:
    runs-on: ubuntu-latest
    container: ros:kilted
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'
          check-latest: true

      - name: Prepare environment
        shell: bash
        run: |
          apt-get update
          apt-get install -y \
            ros-kilted-action-msgs \
            ros-kilted-example-interfaces \
            ros-kilted-test-msgs
          env > "$GITHUB_ENV"

      - uses: golangci/golangci-lint-action@v9
