name: main

env:
  ROS_DISTRO: humble

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/tiiuae/fog-ros-baseimage-builder:sha-7fca749
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - uses: actions/checkout@v3

      - name: Install additional tools and libraries
        run: |
          apt-get update
          apt-get install -y \
            make \
            ros-${ROS_DISTRO}-action-msgs \
            ros-${ROS_DISTRO}-example-interfaces \
            ros-${ROS_DISTRO}-test-msgs

      - name: Run tests
        run: make test

  run-linter:
    runs-on: ubuntu-latest
    container: ghcr.io/tiiuae/fog-ros-baseimage-builder:sha-7fca749
    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        shell: bash
        run: |
          apt-get update
          apt-get install -y \
            ros-${ROS_DISTRO}-action-msgs \
            ros-${ROS_DISTRO}-example-interfaces \
            ros-${ROS_DISTRO}-test-msgs
          env > "$GITHUB_ENV"

      - uses: golangci/golangci-lint-action@v3
