/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

// Code generated by rclgo-gen. DO NOT EDIT.

package action_msgs_srv
import (
	"unsafe"

	"github.com/ATIinc/rclgo/pkg/rclgo"
	"github.com/ATIinc/rclgo/pkg/rclgo/types"
	"github.com/ATIinc/rclgo/pkg/rclgo/typemap"
	service_msgs_msg "github.com/ATIinc/rclgo/internal/msgs/service_msgs/msg"
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <action_msgs/srv/cancel_goal.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("action_msgs/CancelGoal_Event", CancelGoal_EventTypeSupport)
	typemap.RegisterMessage("action_msgs/srv/CancelGoal_Event", CancelGoal_EventTypeSupport)
}

type CancelGoal_Event struct {
	Info service_msgs_msg.ServiceEventInfo `yaml:"info" json:"info" mapstructure:"info"`
	Request []CancelGoal_Request `yaml:"request" json:"request" mapstructure:"request"`
	Response []CancelGoal_Response `yaml:"response" json:"response" mapstructure:"response"`
}

// NewCancelGoal_Event creates a new CancelGoal_Event with default values.
func NewCancelGoal_Event() *CancelGoal_Event {
	self := CancelGoal_Event{}
	self.SetDefaults()
	return &self
}

func (t *CancelGoal_Event) Clone() *CancelGoal_Event {
	c := &CancelGoal_Event{}
	c.Info = *t.Info.Clone()
	if t.Request != nil {
		c.Request = make([]CancelGoal_Request, len(t.Request))
		CloneCancelGoal_RequestSlice(c.Request, t.Request)
	}
	if t.Response != nil {
		c.Response = make([]CancelGoal_Response, len(t.Response))
		CloneCancelGoal_ResponseSlice(c.Response, t.Response)
	}
	return c
}

func (t *CancelGoal_Event) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CancelGoal_Event) SetDefaults() {
	t.Info.SetDefaults()
	t.Request = nil
	t.Response = nil
}

func (t *CancelGoal_Event) GetTypeSupport() types.MessageTypeSupport {
	return CancelGoal_EventTypeSupport
}

// CancelGoal_EventPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type CancelGoal_EventPublisher struct {
	*rclgo.Publisher
}

// NewCancelGoal_EventPublisher creates and returns a new publisher for the
// CancelGoal_Event
func NewCancelGoal_EventPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*CancelGoal_EventPublisher, error) {
	pub, err := node.NewPublisher(topic_name, CancelGoal_EventTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CancelGoal_EventPublisher{pub}, nil
}

func (p *CancelGoal_EventPublisher) Publish(msg *CancelGoal_Event) error {
	return p.Publisher.Publish(msg)
}

// CancelGoal_EventSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type CancelGoal_EventSubscription struct {
	*rclgo.Subscription
}

// CancelGoal_EventSubscriptionCallback type is used to provide a subscription
// handler function for a CancelGoal_EventSubscription.
type CancelGoal_EventSubscriptionCallback func(msg *CancelGoal_Event, info *rclgo.MessageInfo, err error)

// NewCancelGoal_EventSubscription creates and returns a new subscription for the
// CancelGoal_Event
func NewCancelGoal_EventSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback CancelGoal_EventSubscriptionCallback) (*CancelGoal_EventSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg CancelGoal_Event
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, CancelGoal_EventTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &CancelGoal_EventSubscription{sub}, nil
}

func (s *CancelGoal_EventSubscription) TakeMessage(out *CancelGoal_Event) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneCancelGoal_EventSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCancelGoal_EventSlice(dst, src []CancelGoal_Event) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CancelGoal_EventTypeSupport types.MessageTypeSupport = _CancelGoal_EventTypeSupport{}

type _CancelGoal_EventTypeSupport struct{}

func (t _CancelGoal_EventTypeSupport) New() types.Message {
	return NewCancelGoal_Event()
}

func (t _CancelGoal_EventTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.action_msgs__srv__CancelGoal_Event
	return (unsafe.Pointer)(C.action_msgs__srv__CancelGoal_Event__create())
}

func (t _CancelGoal_EventTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.action_msgs__srv__CancelGoal_Event__destroy((*C.action_msgs__srv__CancelGoal_Event)(pointer_to_free))
}

func (t _CancelGoal_EventTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CancelGoal_Event)
	mem := (*C.action_msgs__srv__CancelGoal_Event)(dst)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsCStruct(unsafe.Pointer(&mem.info), &m.Info)
	CancelGoal_Request__Sequence_to_C(&mem.request, m.Request)
	CancelGoal_Response__Sequence_to_C(&mem.response, m.Response)
}

func (t _CancelGoal_EventTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CancelGoal_Event)
	mem := (*C.action_msgs__srv__CancelGoal_Event)(ros2_message_buffer)
	service_msgs_msg.ServiceEventInfoTypeSupport.AsGoStruct(&m.Info, unsafe.Pointer(&mem.info))
	CancelGoal_Request__Sequence_to_Go(&m.Request, mem.request)
	CancelGoal_Response__Sequence_to_Go(&m.Response, mem.response)
}

func (t _CancelGoal_EventTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__action_msgs__srv__CancelGoal_Event())
}

type CCancelGoal_Event = C.action_msgs__srv__CancelGoal_Event
type CCancelGoal_Event__Sequence = C.action_msgs__srv__CancelGoal_Event__Sequence

func CancelGoal_Event__Sequence_to_Go(goSlice *[]CancelGoal_Event, cSlice CCancelGoal_Event__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CancelGoal_Event, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		CancelGoal_EventTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func CancelGoal_Event__Sequence_to_C(cSlice *CCancelGoal_Event__Sequence, goSlice []CancelGoal_Event) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.action_msgs__srv__CancelGoal_Event)(C.malloc(C.sizeof_struct_action_msgs__srv__CancelGoal_Event * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		CancelGoal_EventTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func CancelGoal_Event__Array_to_Go(goSlice []CancelGoal_Event, cSlice []CCancelGoal_Event) {
	for i := 0; i < len(cSlice); i++ {
		CancelGoal_EventTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CancelGoal_Event__Array_to_C(cSlice []CCancelGoal_Event, goSlice []CancelGoal_Event) {
	for i := 0; i < len(goSlice); i++ {
		CancelGoal_EventTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
